<a href="https://colab.research.google.com/github/tytyty93/LazyProgrammer/blob/master/LP_RNN_Shapes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Input, SimpleRNN
from tensorflow.keras.optimizers import SGD, Adam

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [0]:
# Things you should automatically know and have memorized
# N = number of samples
# T = sequence length
# D = number of input features
# M = number of hidden units
# K = number of output units

# Making Dumy Variable

In [0]:
N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N,T,D)

In [10]:
X

array([[[ 0.45125545,  1.57851821,  0.82079193],
        [-1.38244536, -0.45013062,  0.02232191],
        [-2.04574349,  0.55692787,  1.83268995],
        [-0.36556669, -0.89099539, -0.14635618],
        [ 0.0236505 ,  1.42531751, -1.48369518],
        [ 0.5663348 , -0.35926702,  0.65540362],
        [ 1.29218633, -0.72918925,  0.15476168],
        [-0.45814636,  0.12447674, -0.17185031],
        [-1.85239591,  1.1905685 , -0.44014606],
        [ 0.55956207,  0.49581423, -1.13726268]]])

# Making an RNN

In [0]:
M = 5  # No. of hidden layers
i = Input(shape=(T,D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i,x)

# Getting the Output

In [29]:
Yhat = model.predict(X)
print(Yhat)

[[-0.11826549  0.4587659 ]]


In [18]:
Yhat.shape

(1, 2)

In [30]:
model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 10, 3)]           0         
_________________________________________________________________
simple_rnn_3 (SimpleRNN)     (None, 5)                 45        
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 12        
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [32]:
# See what's returned
model.layers[1].get_weights()

[array([[ 5.0421280e-01, -2.8185099e-01,  1.2200183e-01, -8.2636654e-02,
          9.5888734e-02],
        [-7.5057322e-01,  8.3703321e-01,  7.5546235e-01,  7.9166716e-01,
         -3.0803430e-01],
        [-2.0083147e-01, -7.4992365e-01,  6.6216844e-01, -3.3438981e-01,
         -8.3088875e-04]], dtype=float32),
 array([[-0.89939785,  0.31054702,  0.09653234,  0.16005601, -0.24435152],
        [-0.28530592, -0.3599944 , -0.66601056,  0.2831937 ,  0.5150107 ],
        [-0.30102357, -0.75399494,  0.23530075, -0.52470005, -0.10099461],
        [ 0.02957161, -0.34092432,  0.5953963 ,  0.7095615 ,  0.15786654],
        [-0.1348866 ,  0.29870865,  0.37047055, -0.3396995 ,  0.79995906]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [22]:
# Check their shapes
# Should make sense
# First output is input > hidden
# Second output is hidden > hidden
# Third output is bias term (vector of length M)
a, b, c = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)


In [0]:
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [24]:
h_last = np.zeros(M) # initial hidden state
x = X[0] # the one and only sample
Yhats = [] # where we store the outputs

for t in range(T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h.dot(Wo) + bo # we only care about this value on the last iteration
  Yhats.append(y)
  
  # important: assign h to h_last
  h_last = h

# print the final output
print(Yhats[-1])

[0.21894775 1.19865848]
